### ISSUE TITLE
Idea: Prevent "Start" from being ran multiple times

### ISSUE THREAD

**Issue by bnhovde** [whatthefoo/bodyfreeze#1]
Nice idea!

A cool feature would be if the script kept track of whether the body is frozen or not, and then skipped applying/removing the styles if called again. (Maybe with a data-attribute)

I've had problems (with SPA's) where prop changes in parent components caused a re-render and the styles/class to be applied multiple times. Adding styles to body causes a full page reflow, so doing it several times will drop the frame rate.

**Comment by leifriksheim** [comment]
Ah, thank's that's a good point. I'll fix that!
